In [33]:
import calendar
import datetime
import pytz

In [34]:
today = datetime.date.today()
print(today)

2024-08-11

In [35]:
today.year

2024

In [36]:
today.day

11

In [37]:
n= datetime.datetime.now()
print(n)

2024-08-11 21:22:04.264967

In [38]:
print(dir(datetime.datetime))

['__add__', '__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__radd__', '__reduce__', '__reduce_ex__', '__repr__', '__rsub__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', 'astimezone', 'combine', 'ctime', 'date', 'day', 'dst', 'fold', 'fromisoformat', 'fromordinal', 'fromtimestamp', 'hour', 'isocalendar', 'isoformat', 'isoweekday', 'max', 'microsecond', 'min', 'minute', 'month', 'now', 'replace', 'resolution', 'second', 'strftime', 'strptime', 'time', 'timestamp', 'timetuple', 'timetz', 'today', 'toordinal', 'tzinfo', 'tzname', 'utcfromtimestamp', 'utcnow', 'utcoffset', 'utctimetuple', 'weekday', 'year']

In [88]:
dt = datetime.datetime(2016, 7, 24, 12, 30, 45, tzinfo=pytz.UTC)
print(dir(dt))

['__add__', '__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__radd__', '__reduce__', '__reduce_ex__', '__repr__', '__rsub__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', 'astimezone', 'combine', 'ctime', 'date', 'day', 'dst', 'fold', 'fromisocalendar', 'fromisoformat', 'fromordinal', 'fromtimestamp', 'hour', 'isocalendar', 'isoformat', 'isoweekday', 'max', 'microsecond', 'min', 'minute', 'month', 'now', 'replace', 'resolution', 'second', 'strftime', 'strptime', 'time', 'timestamp', 'timetuple', 'timetz', 'today', 'toordinal', 'tzinfo', 'tzname', 'utcfromtimestamp', 'utcnow', 'utcoffset', 'utctimetuple', 'weekday', 'year']

In [91]:
dt_utcnow = datetime.datetime.now(tz=pytz.UTC)

dt_utcnow2 = datetime.datetime.utcnow().replace(tzinfo=pytz.UTC)

dt_mtn = dt_utcnow.astimezone(pytz.timezone('US/Mountain'))

In [94]:
pytz.timezone('US/Mountain')

In [95]:
dt_mtn.astimezone(pytz.timezone('US/Eastern'))

datetime.datetime(2024, 6, 28, 11, 0, 2, 918879, tzinfo=<DstTzInfo 'US/Eastern' EDT-1 day, 20:00:00 DST>)

In [96]:
dt_mtn.strftime('%B %d, %Y')

'June 28, 2024'

In [99]:
day = today.isoweekday()
day

5

In [100]:
weekdays = {1: "Monday",
            2: "Tuesday",
            3: "Wednesday",
            4: "Thursday",
            5: "Friday",
            6: "Saturday",
            7: "Sunday"}

In [104]:
print(today , " " , weekdays[day])

2024-06-28   Friday

In [73]:
today.weekday()

4

In [74]:
datetime.timedelta(days=0, seconds=0, microseconds=0, milliseconds=0, minutes=0, hours=0, weeks=0)

datetime.timedelta(0)

In [75]:
datetime.timedelta(hours=12)

datetime.timedelta(seconds=43200)

In [13]:
print(calendar.month(2024,6,12))

                                        June 2024
   Monday      Tuesday     Wednesday     Thursday      Friday      Saturday      Sunday
                                                                       1            2
      3            4            5            6            7            8            9
     10           11           12           13           14           15           16
     17           18           19           20           21           22           23
     24           25           26           27           28           29           30

In [29]:
print(calendar.weekday(2024,10,24))

3

In [30]:
print(calendar.isleap(2024))

True

In [32]:
print(calendar.leapdays(2002, 2024))

5

In [33]:
print(calendar.calendar(2024))

                                  2024

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
 1  2  3  4  5  6  7                1  2  3  4                   1  2  3
 8  9 10 11 12 13 14       5  6  7  8  9 10 11       4  5  6  7  8  9 10
15 16 17 18 19 20 21      12 13 14 15 16 17 18      11 12 13 14 15 16 17
22 23 24 25 26 27 28      19 20 21 22 23 24 25      18 19 20 21 22 23 24
29 30 31                  26 27 28 29               25 26 27 28 29 30 31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
 1  2  3  4  5  6  7             1  2  3  4  5                      1  2
 8  9 10 11 12 13 14       6  7  8  9 10 11 12       3  4  5  6  7  8  9
15 16 17 18 19 20 21      13 14 15 16 17 18 19      10 11 12 13 14 15 16
22 23 24 25 26 27 28      20 21 22 23 24 25 26      17 18 19 20 21 22 23
29 30                     27 28 29 30 31            24 25 26 27 28 29 30

        July                     August                  September
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
 1  2  3  4  5  6  7                1  2  3  4                         1
 8  9 10 11 12 13 14       5  6  7  8  9 10 11       2  3  4  5  6  7  8
15 16 17 18 19 20 21      12 13 14 15 16 17 18       9 10 11 12 13 14 15
22 23 24 25 26 27 28      19 20 21 22 23 24 25      16 17 18 19 20 21 22
29 30 31                  26 27 28 29 30 31         23 24 25 26 27 28 29
                                                    30

      October                   November                  December
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6                   1  2  3                         1
 7  8  9 10 11 12 13       4  5  6  7  8  9 10       2  3  4  5  6  7  8
14 15 16 17 18 19 20      11 12 13 14 15 16 17       9 10 11 12 13 14 15
21 22 23 24 25 26 27      18 19 20 21 22 23 24      16 17 18 19 20 21 22
28 29 30 31               25 26 27 28 29 30         23 24 25 26 27 28 29
                                                    30 31

In [39]:
print(calendar.setfirstweekday(calendar.TUESDAY))

None

In [42]:
year = int(input("Enter the year"))

month = int(input("Enter th month"))

cal =calendar.month(year, month)
print(cal)

     June 2013
Tu We Th Fr Sa Su Mo
             1  2  3
 4  5  6  7  8  9 10
11 12 13 14 15 16 17
18 19 20 21 22 23 24
25 26 27 28 29 30

In [54]:
dt_str = 'July 24, 2016'
datetime.datetime.strptime(dt_str,'%B %d, %Y')

datetime.datetime(2016, 7, 24, 0, 0)

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('E:\excel\Orders.csv')

In [3]:
data['Order Date'] = pd.to_datetime(data['Order Date'])

In [6]:
data['Order Date'].dt.year.head()

0    2018
1    2018
2    2018
3    2018
4    2018
Name: Order Date, dtype: int64

In [7]:
data['Order Date'].dt.month.head()

0    10
1     3
2     1
3    12
4     8
Name: Order Date, dtype: int64

In [8]:
data['Order Date'].dt.day_name().head()

0    Wednesday
1       Friday
2    Wednesday
3     Thursday
4      Tuesday
Name: Order Date, dtype: object

In [26]:
data['data week']=data['Order Date'].dt.week
data.head()

C:\Users\hp\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:1: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.
  """Entry point for launching an IPython kernel.

,Order ID,Order Date,CustomerName,State,City,date_is_weekend,data week
0,B-26055,2018-10-03,Harivansh,Uttar Pradesh,Mathura,0,40
1,B-25993,2018-03-02,Madhav,Delhi,Delhi,0,9
2,B-25973,2018-01-24,Madan Mohan,Uttar Pradesh,Mathura,0,4
3,B-25923,2018-12-27,Gopal,Maharashtra,Mumbai,0,52
4,B-25757,2018-08-21,Vishakha,Madhya Pradesh,Indore,0,34

In [30]:
data['data week']=data['Order Date'].dt.quarter
data.drop(columns=['City']).head()

  Order ID Order Date CustomerName           State  date_is_weekend  data week
0  B-26055 2018-10-03    Harivansh   Uttar Pradesh                0          4
1  B-25993 2018-03-02       Madhav           Delhi                0          1
2  B-25973 2018-01-24  Madan Mohan   Uttar Pradesh                0          1
3  B-25923 2018-12-27        Gopal     Maharashtra                0          4
4  B-25757 2018-08-21     Vishakha  Madhya Pradesh                0          3

In [21]:
data['date_is_weekend']=np.where(data['Order Date'].isin(['Friday','Sunday','Wednesday']),1,0)
data.drop(columns=['Order ID'])

    Order Date CustomerName             State     City  date_is_weekend
0   2018-10-03    Harivansh     Uttar Pradesh  Mathura                0
1   2018-03-02       Madhav             Delhi    Delhi                0
2   2018-01-24  Madan Mohan     Uttar Pradesh  Mathura                0
3   2018-12-27        Gopal       Maharashtra   Mumbai                0
4   2018-08-21     Vishakha    Madhya Pradesh   Indore                0
..         ...          ...               ...      ...              ...
495 2018-03-08       Ashwin               Goa      Goa                0
496 2018-03-26       Bhavna            Sikkim  Gangtok                0
497 2018-01-07      Shivani       Maharashtra   Mumbai                0
498 2018-08-22      Shubham  Himachal Pradesh    Simla                0
499 2018-03-28      Monisha         Rajasthan   Jaipur                0

[500 rows x 5 columns]